In [2]:
%%HTML
<style>
    body {
        --vscode-font-family: 霞鹜文楷, Consolas, 'Courier New', monospace
    }
</style>

# 1. 张量Tensor

In [3]:
from __future__ import print_function
import torch

In [20]:
x = torch.rand(4, 6)
print(x)

tensor([[0.8617, 0.8457, 0.5429, 0.1825, 0.7598, 0.8036],
        [0.0964, 0.6414, 0.5835, 0.6622, 0.0689, 0.7618],
        [0.2493, 0.5965, 0.7201, 0.9501, 0.0989, 0.4248],
        [0.3908, 0.1591, 0.4818, 0.7834, 0.9737, 0.0210]])


In [21]:
print(f'x.size = {x.size(0)}')
print(f'x.shape = {x.shape[0]}')
x[0]

x.size = 4
x.shape = 4


tensor([0.8617, 0.8457, 0.5429, 0.1825, 0.7598, 0.8036])

In [26]:
y = x.view(24)
z = x.view(2,-1)
print(y)
print(z)

tensor([0.8617, 0.8457, 0.5429, 0.1825, 0.7598, 0.8036, 0.0964, 0.6414, 0.5835,
        0.6622, 0.0689, 0.7618, 0.2493, 0.5965, 0.7201, 0.9501, 0.0989, 0.4248,
        0.3908, 0.1591, 0.4818, 0.7834, 0.9737, 0.0210])
tensor([[0.8617, 0.8457, 0.5429, 0.1825, 0.7598, 0.8036, 0.0964, 0.6414, 0.5835,
         0.6622, 0.0689, 0.7618],
        [0.2493, 0.5965, 0.7201, 0.9501, 0.0989, 0.4248, 0.3908, 0.1591, 0.4818,
         0.7834, 0.9737, 0.0210]])


In [28]:
x1 = torch.randn(1)
print(x1.item())

0.05162752792239189


# 2. 自动微分

In [30]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [33]:
y = x / 2
print(y)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]], grad_fn=<DivBackward0>)


In [34]:
print(y.grad_fn)

In [42]:
z = y * y * 3
out = z.mean()
print(z,'\n',out)

tensor([[0.7500, 0.7500],
        [0.7500, 0.7500]], grad_fn=<MulBackward0>) 
 tensor(0.7500, grad_fn=<MeanBackward0>)


In [47]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
True
tensor(6.1583, grad_fn=<SumBackward0>)


In [48]:
out = b.mean()
out.backward()

In [49]:
print(x.grad)#d(out)/dx

tensor([[0.3750, 0.3750],
        [0.3750, 0.3750]])


In [56]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -162.8658,  -496.3813, -1358.8882], grad_fn=<MulBackward0>)


In [57]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
